### PR TITLE
Shorten bashCommand as much as possible

### PR DESCRIPTION
**Pull request by 1lastBr3ath**
Might come handy when there's a limit to payload length.

### CODE REVIEW

**Comment by 1lastBr3ath** [comment]
The reason I chose 57 for `base64` wrap is to limit the label length to 63, at max. Since you're adding `E-F` and replacing `+` with `PLUS`, it's just accounting the number of added chars i.e. 57+3+3 = 63.

**Comment by 0xC01DF00D** [comment]
I chose to use the openssl base64 due to some older linux machines not having "base64" installed natively. Same with bash. Since some servers don't use bash, I chose to return results using sh. I want to make sure the compatibility is maximized. I do like the reduction in label limit for base64 though. 

In my experience, more systems have openSSL installed than the base64 native package, and the systems being targeted aren't always up to date distros.

**Comment by 1lastBr3ath** [comment]
Well! You're already using `base64` in the `bashCommand`.

**Comment by 0xC01DF00D** [comment]
I didn't notice I was already using base64 in the command. Whoops!

I will do some research on which distros didn't have it by default and make a decision.

**Review by 0xC01DF00D — APPROVED** [review]

**Review by 0xC01DF00D — APPROVED** [review]

**Pull request closed without merging**
